<?php
/**
 * Common functions used by both autoload.php and generate.php scripts.
 *
 * @author    M.Olszewski
 * @since     2010-03-26
 * @copyright Copyright (c) 2010 by M.Olszewski. All rights reserved.
 */


require_once dirname(__FILE__) . '/autoload/FileIndexStorage.php';
require_once dirname(__FILE__) . '/autoload/CompressedFileIndexStorage.php';


/**
 * Gets path to the index storage, either default one (generated by call to
 * {@link autoload_get_default_index_path()} or the one defined in PHP_AUTOLOADER_INDEX_PATH variable.
 *
 * @return string Returns path to the index storage.
 */
function autoload_get_index_path()
{
  $path = null;
  if (false == defined('PHP_AUTOLOADER_INDEX_PATH'))
  {
    // get default index path
    $path = autoload_get_default_index_path();
  }
  else
  {
    $path = PHP_AUTOLOADER_INDEX_PATH;
  }

  return $path;
}

/**
 * Gets default path to the index storage, based upon path to calling script.
 *
 * @return string Returns default path to the index storage.
 */
function autoload_get_default_index_path()
{
  $caller = filter_var($_SERVER['SCRIPT_FILENAME'], FILTER_SANITIZE_STRING);
  $dir    = dirname(realpath($caller));
  $name   = md5($dir);
  $ext    = '.idx';

  return $dir . '/' . $name . $ext;
}

function autoload_get_index_storage($path)
{
  if (is_string($path) == false)
  {
    throw new InvalidArgumentException(__FUNCTION__ . '(): $path is not a string! $path=' . $path);
  }

  $storage = null;
  if (false == defined('PHP_AUTOLOADER_INDEX_STORAGE_NO_COMPRESSION'))
  {
    $storage = new autoload_CompressedFileIndexStorage(new SplFileInfo($path));
  }
  else
  {
    $storage = new autoload_FileIndexStorage(new SplFileInfo($path));
  }

  return $storage;
}
